# Site variables

url: "https://kolchinmax.ru"

# Others
remote_theme: yous/whiteglass
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  sass_dir: ./_scss

google_analytics: "UA-50833208-1"

safe: true
exclude: [vendor, CNAME, Gemfile, Gemfile.lock, .gitignore, .idea, docker-compose.yml]

# Content variables
author: Maksim Kolchin
title: Maksim Kolchin
